In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [2]:
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,New Norfolk,-42.78,147.06,51.01,69,34,2.42,AU,2020-10-31 19:45:46
1,1,Chokurdakh,70.63,147.92,-4.67,92,98,7.90,RU,2020-10-31 19:48:27
2,2,Waipawa,-41.41,175.52,61.00,72,6,16.11,NZ,2020-10-31 19:48:27
3,3,Taoudenni,22.68,-3.98,81.73,16,100,10.63,ML,2020-10-31 19:48:27
4,4,Sinnamary,5.38,-52.95,84.22,71,100,11.86,GF,2020-10-31 19:48:28

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
#for temp in max_temp:
    #temps.append(max(temp, 0))

#heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
#heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
# heat_layer = gmaps.heatmap_layer(locations, weights=temps)
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)


# Add the heatmap layer.
fig.add_layer(heat_layer)


fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudy
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
weight=clouds
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent windy
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
weights=wind
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
3,3,Taoudenni,22.68,-3.98,81.73,16,100,10.63,ML,2020-10-31 19:48:27
4,4,Sinnamary,5.38,-52.95,84.22,71,100,11.86,GF,2020-10-31 19:48:28
5,5,Santa Barbara,34.73,-120.03,87.01,18,1,3.36,US,2020-10-31 19:48:28
6,6,Dire,12.28,-10.97,80.04,42,71,2.57,ML,2020-10-31 19:48:28
8,8,Touros,-5.20,-35.46,84.20,70,40,14.99,BR,2020-10-31 19:46:31
10,10,Mana,5.66,-53.78,85.10,69,62,14.07,GF,2020-10-31 19:48:29
11,11,Avarua,-21.21,-159.78,75.20,78,100,10.29,CK,2020-10-31 19:48:29
14,14,Dunkwa,5.97,-1.78,75.29,93,54,2.53,GH,2020-10-31 19:48:29
15,15,Rikitea,-23.12,-134.97,75.24,69,0,6.87,PF,2020-10-31 19:48:30
23,23,Kapaa,22.08,-159.32,82.00,78,1,6.87,US,2020-10-31 19:47:50

In [12]:
preferred_cities_df.count()

City_ID       166
City          166
Lat           166
Lng           166
Max Temp      166
Humidity      166
Cloudiness    166
Wind Speed    166
Country       165
Date          166
dtype: int64

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp    Lat     Lng Hotel Name
3       Taoudenni      ML     81.73  22.68   -3.98
4       Sinnamary      GF     84.22   5.38  -52.95
5   Santa Barbara      US     87.01  34.73 -120.03
6            Dire      ML     80.04  12.28  -10.97
8          Touros      BR     84.20  -5.20  -35.46
10           Mana      GF     85.10   5.66  -53.78
11         Avarua      CK     75.20 -21.21 -159.78
14         Dunkwa      GH     75.29   5.97   -1.78
15        Rikitea      PF     75.24 -23.12 -134.97
23          Kapaa      US     82.00  22.08 -159.32

In [28]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
print(hotels)

{'html_attributions': [], 'next_page_token': 'AcnaJv2z7fq6IPqpfYnW2_rroGdrsVRe7ct_jJGcEI09jxb4LfvOIhjqkkL56zL26OsXia1ryx3KLr9inS813isy27DHBCYJXnsY_N2FqGjoFXrLtBofI-TB6OvAtGpM5teLrRsZ--tFQ73h3wCFHoW8lG7CXrHJFrYCWS2dVu4X-Ayojgom3pJYDdqGe81yDlt4tgICImkpvYJpdRLPsDxL2F9mHRC5hOehe5kh9pu7GOP_fr7fbWjFHRTQqT1k0W_m-JnNySb6nxCZhBkNyibjKqZ9mWkroQMDx6dsUyIOrGEjfBVy3l4j77QNLVyDihqsRiXIluq2Q22nho12JGPXyZgfPD7hhcRijjoj6ABhGRSocUMGNtDhM9lq8KCPoOXcT1u5KIbeu8qs6ba6kNOwBaEbvWtl1c2IVz914m6SNTYCn27g_rI', 'results': [{'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277}, 'viewport': {'northeast': {'lat': 48.8594393802915, 'lng': 2.354352980291502}, 'southwest': {'lat': 48.8567414197085, 'lng': 2.351655019708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Duo', 'opening_hours': {'open_now': True}, 'photos': [{'height': 3840, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'], 'photo_reference': 'CmRaAAAA2bQwa0tBO9IsR-Flbmf57s4YvpRN6y-2TBJXynlA6tyHga_ztG9cFloGs4szOFct83fg1MdC3UBJ09B6OowYZQwLa_TUi64S0hxsx4emxe3mbYOrtVGE-MMxi7LHEpeDEhC32bYZKPAhAS_uZGobwnd6GhTHMRVTsSf786zbzGF12ofdUV81Iw', 'width': 5760}], 'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc', 'plus_code': {'compound_code': 'V953+65 Paris, France', 'global_code': '8FW4V953+65'}, 'rating': 4.2, 'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc', 'scope': 'GOOGLE', 'types': ['night_club', 'spa', 'lodging', 'bar', 'gym', 'health', 'point_of_interest', 'establishment'], 'user_ratings_total': 277, 'vicinity': '11 Rue du Temple, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944}, 'viewport': {'northeast': {'lat': 48.8595495802915, 'lng': 2.347780980291502}, 'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Britannique', 'opening_hours': {'open_now': True}, 'photos': [{'height': 546, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Louvre</a>'], 'photo_reference': 'CmRaAAAAxBiS8Sw1HMkwZn79mZk71--HfvVCg4YeZDMCxJH_JHtUJ24Dy01w-dcmZ3IHiprm_j-NEKhP_sj9o0l-v4V4y3Spbli_cDOq5TajM1PCrDeUJXYE4eEnbPGdJJsPmKrXEhBRA5RTWWY4Z0WmO3Ovjbm_GhThU0tR-ejZ1ZUTyOqz7sVCQgd0Hg', 'width': 1024}], 'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU', 'plus_code': {'compound_code': 'V85W+8H Paris, France', 'global_code': '8FW4V85W+8H'}, 'rating': 4.6, 'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 366, 'vicinity': '20 Avenue Victoria, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293}, 'viewport': {'northeast': {'lat': 48.8618387802915, 'lng': 2.348475730291502}, 'southwest': {'lat': 48.85914081970851, 'lng': 2.345777769708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Citadines Les Halles Paris (Apart Hotel Paris)', 'opening_hours': {'open_now': True}, 'photos': [{'height': 496, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart Hotel Paris)</a>'], 'photo_reference': 'CmRaAAAA7Zb_1-N4hfgU5G_gs583IMoS6iuiiLIai6Iu4kh0Qv-Ll1gDUc0cZLu5nHdV2-akC8oN78XccSrlMNgjc8X2vHPUguysMgw1kdZAaH7dJ6jfvLRTT-6cPATd0JCojl43EhBCPYjzrwXPZvl41iRTBj1KGhQ10zSd2uyX7yjQqWuyGSiWOu4bLg', 'width': 745}], 'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU', 'plus_code': {'compound_code': 'V86W+7Q Paris, France', 'global_code': '8FW4V86W+7Q'}, 'rating': 4.1, 'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 815, 'vicinity': '4 Rue des Innocents, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8607769, 'lng': 2.3463217}, 'viewport': {'northeast': {'lat': 48.8620135802915, 'lng': 2.347597080291502}, 'southwest': {'lat': 48.8593156197085, 'lng': 2.344899119708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Novotel Paris Les Halles', 'opening_hours': {'open_now': True}, 'photos': [{'height': 2000, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'], 'photo_reference': 'CmRaAAAAYxUfXm_-veiBVfnW0cDM_SslcjXhP__qKurQyt4Nwwu-tJdRjUrCvfeGQV66qn60D6dA-CegQxhPmxh60rcKThF6oZs6m_0dpTdFNRmlvUnk_frhBxGW7K83bN8zLIZCEhBhU3_La_ZPbcx0r0cg55bJGhRLEdvmhA0lYIhFUnV2a4VGc34sWg', 'width': 3000}], 'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ', 'plus_code': {'compound_code': 'V86W+8G Paris, France', 'global_code': '8FW4V86W+8G'}, 'rating': 4.4, 'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 2077, 'vicinity': '8 Place Marguerite de Navarre, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054}, 'viewport': {'northeast': {'lat': 48.8616503302915, 'lng': 2.345521080291502}, 'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Ducs de Bourgogne', 'opening_hours': {'open_now': True}, 'photos': [{'height': 1390, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Best Western Premier Ducs de Bourgogne</a>'], 'photo_reference': 'CmRaAAAAQpcej9a8oaP3klSE7KnE9oA4pA3XbT7ilrld8PVZTKW18_TcshL43oyXq-HQvKlKLuoHRqxrNfR6oPlYB9nW1Adm7SUtZSInt9_yiQLwdiUUJedacYp2HjtUpB_ESC4ZEhCscwu3nBjUMdA7S-8IFFcBGhQd97Za6lQOr1dbjhyLjv7tmZRE9A', 'width': 2048}], 'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4', 'plus_code': {'compound_code': 'V86V+4J Paris, France', 'global_code': '8FW4V86V+4J'}, 'rating': 4.5, 'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 274, 'vicinity': '19 Rue du Pont Neuf, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736}, 'viewport': {'northeast': {'lat': 48.8569076302915, 'lng': 2.342319280291502}, 'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Citadines Saint-Germain-des-Prés Paris', 'opening_hours': {'open_now': True}, 'photos': [{'height': 3024, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107856881779358840274">David O&#39;Meara</a>'], 'photo_reference': 'CmRaAAAACpKItU131xlGkRmPV0Cfqlln03b9qOFk2CwsHlWRpSZ0r2q001b6Q1rUu5c9cLg3LT9pkNHnPgaAcx4lU6C4v9Dfx8x1Q7V35CnVcjPYTAsPR2Ub8n9_YwINHFdAgpzYEhBdR5pS9ydNOKtHSAkTGyH-GhSnX_qypZZDezrF6NUwayZIBkugsA', 'width': 4032}], 'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE', 'plus_code': {'compound_code': 'V84R+68 Paris, France', 'global_code': '8FW4V84R+68'}, 'rating': 4.3, 'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 650, 'vicinity': '53 ter Quai des Grands Augustins, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.86634659999999, 'lng': 2.36064}, 'viewport': {'northeast': {'lat': 48.8677623302915, 'lng': 2.361952180291502}, 'southwest': {'lat': 48.86506436970851, 'lng': 2.359254219708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Paris France Hôtel', 'opening_hours': {'open_now': True}, 'photos': [{'height': 2673, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'], 'photo_reference': 'CmRaAAAAY0OWKLJqt6ypJQgJMIeqjyIotP-Wt1V1LmeSp5Toz76cS_hcsbfAcLFZ1dOz7UdigQFRQOz-kDXmaM6UydOwC_5J4EJpxvF1R216z5edsYYxzd_U7U9jhOHjqSBcdAfPEhDAT82Ca3iqL0xNDLOeBTX0GhT5zgc0DB3N-PATYP2spvk77lNN9Q', 'width': 3463}], 'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg', 'plus_code': {'compound_code': 'V986+G7 Paris, France', 'global_code': '8FW4V986+G7'}, 'rating': 4.3, 'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 375, 'vicinity': '72 Rue de Turbigo, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488}, 'viewport': {'northeast': {'lat': 48.8652309302915, 'lng': 2.333762030291502}, 'southwest': {'lat': 48.8625329697085, 'lng': 2.331064069708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hotel Regina Louvre', 'opening_hours': {'open_now': True}, 'photos': [{'height': 3700, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109066439891801774697">Hôtel Regina Louvre</a>'], 'photo_reference': 'CmRaAAAA88D9J61EuYdTELSr0wV4AEM0TiFndnArSTWfnTdSly5oQyfkW1hOFaYFISVCURyOTmQf9VPeZba8C2OyQLqiV0qRSqA8ORIe3Wdli8HMc8A8wswDLoLZyjEwgVfNTLvREhDHflhxy8QvrWEYnr7GaA1zGhSa3zdMN1C2cse_8g3vSEk-17w-jw', 'width': 5550}], 'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w', 'plus_code': {'compound_code': 'V87M+G2 Paris, France', 'global_code': '8FW4V87M+G2'}, 'rating': 4.5, 'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w', 'scope': 'GOOGLE', 'types': ['lodging', 'bar', 'restaurant', 'food', 'point_of_interest', 'establishment'], 'user_ratings_total': 500, 'vicinity': '2 Place des Pyramides, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869}, 'viewport': {'northeast': {'lat': 48.84922153029149, 'lng': 2.372321980291502}, 'southwest': {'lat': 48.84652356970849, 'lng': 2.369624019708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème', 'opening_hours': {'open_now': True}, 'photos': [{'height': 3024, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102166088584622554231">cherry pyj</a>'], 'photo_reference': 'CmRaAAAA7DYNzsftYHqcgIOANcXjaLhyfoTfg1p2mSG4F-gBilFD6yKMSzVmRyLP7PDa0TMB4qOrlrwMf-wZSSjbDVNjEaKT5K7TMD08tJ2aexNyB1GLdrRzewV3EpKKBeBnzCuOEhCOtcA_TB9d6fn5Elc2BWuvGhTPa8_LhCH9Oso_-lmJBLGUsaLviQ', 'width': 4032}], 'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow', 'plus_code': {'compound_code': 'R9XC+58 Paris, France', 'global_code': '8FW4R9XC+58'}, 'rating': 4, 'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 743, 'vicinity': '41/43 Avenue Ledru Rollin, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8475464, 'lng': 2.3718722}, 'viewport': {'northeast': {'lat': 48.8488750302915, 'lng': 2.373125480291502}, 'southwest': {'lat': 48.8461770697085, 'lng': 2.370427519708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel De France Gare de Lyon Bastille', 'photos': [{'height': 1960, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104045426349853231072">michael scanlon</a>'], 'photo_reference': 'CmRaAAAAayjNr9VioFNRKD-60e_hvWwgbbGbeXyySZvKhtwpts9u0DO-CfVZzY7ewmt0lEJNCZQ6gZRWMZ-tE1gJpsK3C-lxO2BaLVVp9n9khg3fwEqsAg4Rk4Sx69k50ereeExiEhBU8agYg595kZTMHk02HGz2GhQlMve6sZGXjgjhfEZnoo_1DO1SEg', 'width': 4032}], 'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM', 'plus_code': {'compound_code': 'R9XC+2P Paris, France', 'global_code': '8FW4R9XC+2P'}, 'rating': 3.3, 'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 380, 'vicinity': '12 Rue de Lyon, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052}, 'viewport': {'northeast': {'lat': 48.8731394302915, 'lng': 2.346067130291502}, 'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Corona Opéra', 'photos': [{'height': 4000, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110158133027602673318">Marisa Pretto</a>'], 'photo_reference': 'CmRaAAAAmiUDyMWblal_0nIPmdM4NS1_-NSPXstTI3rLRcHOcNe67n6_Pk26dbHObL8zjA301F05drHSIPfBpFpdw9ZK0EzyFQV1uB8ecSL385hLK8SViisGLJ5Vs1z8MOonM1hrEhBvzYt6RhiDI4e0l_DEFi-QGhSWOPTiyiTMdc7heZS033BpsXvfSg', 'width': 3000}], 'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk', 'plus_code': {'compound_code': 'V8CV+MV Paris, France', 'global_code': '8FW4V8CV+MV'}, 'rating': 4, 'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 309, 'vicinity': '8 Cité Bergère, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8423491, 'lng': 2.3632246}, 'viewport': {'northeast': {'lat': 48.84365308029151, 'lng': 2.364707180291502}, 'southwest': {'lat': 48.84095511970851, 'lng': 2.362009219708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Libertel Austerlitz Jardin des Plantes', 'opening_hours': {'open_now': True}, 'photos': [{'height': 4480, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'], 'photo_reference': 'CmRaAAAAeqy423QMIMestJRcQ9V05sQIJaw8VJRVb8jwggCc8Uq2vhkdfWBXNrfUSv8pbs0ntwuELiIMUWE4woExPZVT1-zcQOfz2yHI38i5vccTDm3XUeAw3BCLJh7G68W-WvtQEhAGLv38E5SpD2Otm9jcN3AxGhRwhRiaJrvnaxFUOaG1bq1mo0nSeA', 'width': 6720}], 'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw', 'plus_code': {'compound_code': 'R9R7+W7 Paris, France', 'global_code': '8FW4R9R7+W7'}, 'rating': 4, 'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 434, 'vicinity': "12 Boulevard de l'Hôpital, Paris"}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997}, 'viewport': {'northeast': {'lat': 48.8655898302915, 'lng': 2.332108780291502}, 'southwest': {'lat': 48.8628918697085, 'lng': 2.329410819708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Saint James Albany Paris Hôtel Spa', 'opening_hours': {'open_now': True}, 'photos': [{'height': 1365, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'], 'photo_reference': 'CmRaAAAAiiMkKvV5X6FAOWh5Yd60xDnoGEbLC6pmz_jgtXQfudmUkJJ7-uGx5fVgbF-xGKwKqhxmBylMbDLtLmIQ-srasmPsfBXeTCkPnqCI7SdygqTDpffuUvE9FVO18p4EkjB9EhA54S-TZFeqcCjpY7aYf_X2GhQeXpyc51L0SWxGI0Pe2gke9M5ZHg', 'width': 2048}], 'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs', 'plus_code': {'compound_code': 'V87J+P8 Paris, France', 'global_code': '8FW4V87J+P8'}, 'rating': 4, 'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs', 'scope': 'GOOGLE', 'types': ['lodging', 'bar', 'restaurant', 'food', 'point_of_interest', 'establishment'], 'user_ratings_total': 1070, 'vicinity': '202 Rue de Rivoli, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728}, 'viewport': {'northeast': {'lat': 48.8724296802915, 'lng': 2.340311330291502}, 'southwest': {'lat': 48.8697317197085, 'lng': 2.337613369708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Icône', 'opening_hours': {'open_now': True}, 'photos': [{'height': 1066, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'], 'photo_reference': 'CmRaAAAAEJi0Iz2E_NQOpIyeSdfQp7-AAzC_OPAwlodZ_09lk2rl7jKBq06p7UQJ56BW5XhHzBJO-pd4D-rAXekW0ZHjLSjiTxTMwhkJkAHMwPPCGyGkJMhd4ItE5Mu4kR99w530EhBumMIckNOuhh8EvDyTAJ0QGhTv15_Cg10X2tXVf_etL_iPJGftkQ', 'width': 1600}], 'place_id': 'ChIJpQvq5Dtu5kcR0COam2f7v_I', 'plus_code': {'compound_code': 'V8CQ+CH Paris, France', 'global_code': '8FW4V8CQ+CH'}, 'rating': 3.7, 'reference': 'ChIJpQvq5Dtu5kcR0COam2f7v_I', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 135, 'vicinity': "4 Rue d'Amboise, Paris"}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8654924, 'lng': 2.3271121}, 'viewport': {'northeast': {'lat': 48.8667867302915, 'lng': 2.328593580291502}, 'southwest': {'lat': 48.8640887697085, 'lng': 2.325895619708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'The Westin Paris - Vendôme', 'opening_hours': {'open_now': True}, 'photos': [{'height': 810, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110604580348447711691">The Westin Paris - Vendôme</a>'], 'photo_reference': 'CmRaAAAAm9BWKs_dFO42HF4nayiQwHEIR2-aMYvSZ0tSPZfjKdVeuTamx2QxlU7cXmGWKxY_-lTsrooei3XIQqHQUTVWC33aU3-ky2CPEC2jlfs5nB_bukx7n4R1HCGmhWN2obEmEhAE4eBI6xzhYKsbljljC0RTGhQWa8IJWwYuT2S7qjFwqbzsyKlw-Q', 'width': 1440}], 'place_id': 'ChIJt4LY5C1u5kcRvVeuJebPxHc', 'plus_code': {'compound_code': 'V88G+5R Paris, France', 'global_code': '8FW4V88G+5R'}, 'rating': 4.4, 'reference': 'ChIJt4LY5C1u5kcRvVeuJebPxHc', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 2031, 'vicinity': '3 Rue de Castiglione, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.86038899999999, 'lng': 2.323112}, 'viewport': {'northeast': {'lat': 48.8617804302915, 'lng': 2.324489280291502}, 'southwest': {'lat': 48.8590824697085, 'lng': 2.321791319708499}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': "Hôtel d'Orsay", 'opening_hours': {'open_now': True}, 'photos': [{'height': 768, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115556676131195822021">Hôtel 4 étoile d&#39;Orsay Paris 7ème</a>'], 'photo_reference': 'CmRaAAAAzE4YKbNqTnEqpD3Lc_JdPzy9Im9BWtWV7PLdJD16T0Mk6VQdohYxOgsqVuGLJYyQUkFcKNhif4wXcXbP5gvPz_5W1OqNzHfOaQ2COaBxCZtfNRawdF9OJzSY9IfW-WfpEhCK-ZfEsWWhT2JIvvkImOR9GhRX-iRMmqMI2gS-tJB-EXnBHalg3A', 'width': 1152}], 'place_id': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k', 'plus_code': {'compound_code': 'V86F+56 Paris, France', 'global_code': '8FW4V86F+56'}, 'rating': 4.6, 'reference': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 207, 'vicinity': '93 Rue de Lille, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8661363, 'lng': 2.3260648}, 'viewport': {'northeast': {'lat': 48.8674534302915, 'lng': 2.327513280291502}, 'southwest': {'lat': 48.8647554697085, 'lng': 2.324815319708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'name': 'Hôtel Mayfair Paris', 'opening_hours': {'open_now': True}, 'photos': [{'height': 1365, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113789389085635834164">Hôtel Mayfair Paris</a>'], 'photo_reference': 'CmRaAAAAe9aK8A0Fuy_OtU4OjuBb2ELDYrwV28DObxinS0L4reurmNT0pVI3hY4WP2vUFXqQKsHYeuWOp1zVjOwaDOLDE08I0Iwdf-gjrMhJv8tXX9iB1DImfqqvpB8z1uaS5sbMEhCqA_MQY-ZRo1QCy6fQq5yaGhRH95L0S2Qsq9SqSE-O37LMW4U0kw', 'width': 2048}], 'place_id': 'ChIJTXVIhS1u5kcRlm9-RG0srQs', 'plus_code': {'compound_code': 'V88G+FC Paris, France', 'global_code': '8FW4V88G+FC'}, 'rating': 4.2, 'reference': 'ChIJTXVIhS1u5kcRlm9-RG0srQs', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 245, 'vicinity': '3 Rue Rouget de Lisle, Paris'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 48.8758937, 'lng': 2.3591167}, 'viewport': {'northeast': {'lat': 48.8772932302915, 'lng': 2.360447230291502}, 'southwest': {'lat': 48.8745952697085, 'lng': 2.357749269708498}}}, 'icon': 'https://map

In [24]:
len(hotels["results"])

20

In [40]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    #print(lat)
    #print(lng)
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    #print(base_url)
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    #print(hotels)
    # Grab the first hotel from the results and store the name.
    #hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (KeyError, IndexError):
        print("Hotel not found... skipping.")
print(hotel_df)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
              City Country  Max Temp    Lat     Lng  \
3        Taoudenni      ML     81.73  22.68   -3.98
4        Sinnamary      GF     84.22   5.38  -52.95
5    Santa Barbara      US     87.01  34.73 -120.03
6             Dire      ML     80.04  12.28  -10.97
8           Touros      BR     84.20  -5.20  -35.46
..             ...     ...       ...    ...     ...
535          Guane      CU     85.24  22.20  -84.09
540          Kanbe      MM     77.00  16.71   96.00
542        Karaton      ID     80.01  -6.34  106.10
543          Alofi      NU     75.20 -19.06 -169.92
545   Port Moresby      PG     77.00  -9.44  147.18

                                Hotel Name
3
4           ALETHEIA Appartement Sinnamary
5                 Upper Ballard Campground
6
8                          INN NEW HORIZON
..                                     ...
535  base de Campismo LosPortales de Guane
540            CBT Mingalar Bar Bio Garden
542     Parkir Mobil Wisata CAS Water Park
543                          Taloa Heights
545                           Lamana Hotel

[166 rows x 6 columns]

In [41]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Taoudenni,ML,81.73,22.68,-3.98,
4,Sinnamary,GF,84.22,5.38,-52.95,ALETHEIA Appartement Sinnamary
5,Santa Barbara,US,87.01,34.73,-120.03,Upper Ballard Campground
6,Dire,ML,80.04,12.28,-10.97,
8,Touros,BR,84.20,-5.20,-35.46,INN NEW HORIZON
...,...,...,...,...,...,...
535,Guane,CU,85.24,22.20,-84.09,base de Campismo LosPortales de Guane
540,Kanbe,MM,77.00,16.71,96.00,CBT Mingalar Bar Bio Garden
542,Karaton,ID,80.01,-6.34,106.10,Parkir Mobil Wisata CAS Water Park
543,Alofi,NU,75.20,-19.06,-169.92,Taloa Heights
545,Port Moresby,PG,77.00,-9.44,147.18,Lamana Hotel